name = "changli"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

account_id = "05f49c4336ab8d1df4fabeeebbcdb083"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "5067ad020c154b56966b5e6726f8bc4c"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "aacac2d2-cac8-442a-9f2c-4e4f807065f5"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/Mayumiwandi/Changli/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/Mayumiwandi/Changli/refs/heads/main/web/sub.html"
